### PR TITLE
Nintendo 3DS port

### PR DESCRIPTION
**Pull request by asiekierka**
Will probably require squashing.

Should be fully functional, although the pad.config might require some tweaking, as in this version (unlike the DS version, which the pad.config is derived from) the keyboard has function keys and modifiers available.

This is more for review than direct pulling, as it's still WIP - when I get my hands on a 3DS, I want to experiment with using geometry shaders for performance improvements (I'm afraid the emulator I have doesn't support it), as well as minor performance tweaks. (I don't think it will run _red_, though)

### CODE REVIEW

**Comment by asiekierka** [comment]
I'd like to point out that https://github.com/AliceLR/megazeux/pull/12/commits/4f8f46c7e5bc936f775fff1d1f4b70c6db973a47 and https://github.com/AliceLR/megazeux/pull/12/commits/bcc6e9ba6b9d8e081483bbcd9407cb2ee73de4f5 are generic fixes which may be beneficial to more ports than just this one.

**Comment by asiekierka** [comment]
Oh.

Uh.

I really should make sure it works great again. But I think it does.

**Comment by asiekierka** [comment]
I have now tested the 3DS port. Works great, should be release-ready especially with the XMP size reduction. However, I don't think the editor works - but that's not a particularly large concern, who's going to try and make games on this?

**Comment by asiekierka** [comment]
In addition, in regards to the platform_matrix update - an SDL-based port for the Nintendo 3DS is possible, just like the Wii, however it would have many of the same issues (high executable size, sub-par performance, etc), as well as lacking all of the port-specific functionality added to date (virtual keyboard, screen dragging, etc).

**Comment by AliceLR** [comment]
I don't think it's a big deal that the editor doesn't work; I haven't actually verified that the editor DOES work on the other platforms with that note.

I haven't had a chance to test my 3DS builds on an actual 3DS yet, but they run to some degree in Citra (audio doesn't work for some reason...).

I think you're right that an updated SDL note in platform_matrix for the 3DS is worthwhile to explain those points.  The Wii has a similar situation, but getting SDL working for it would at least give it layer rendering support until Mr_Alert finishes whatever rewrites he has planned for the gx renderer.  The idea of a PSP hardware renderer is also appealing; do you think it's worth moving PSP off SDL altogether, or just the renderer?

**Comment by asiekierka** [comment]
>audio doesn't work for some reason

That is correct, audio does not work in Citra. Getting a copy of dspfirm.cdc off a real 3DS and putting it in Citra's /3ds folder might help, but I'm not sure if it doesn't just not work at all.

>until Mr_Alert finishes whatever rewrites he has planned for the gx renderer

Mr_Alert's back? Hooray - finally someone who can fix the Wii port!

>do you think it's worth moving PSP off SDL altogether, or just the renderer?

Once you start moving the renderer off SDL, it's not difficult to move the rest off it. Probably worth it.

I'm willing to work on a hardware PSP renderer as soon as I get my hands on a hacked/hackable PSP or PS Vita - with the latter, I also want to work on a simple, software/SDL-based PS Vita port.

**Pull request merged**
