### PR TITLE
Added new CustomNS and CustomEW slider types

### PR DESCRIPTION
**Pull request by flarn2006**
I've always thought this feature was sorely missing.

### CODE REVIEW

**Comment by AliceLR** [comment]
Hi, thanks for submitting this. However, I'm not convinced new types for this would add much since you can already effectively achieve this with regular sliders and many other types:

1. From the editor, `G` → `Edit Chars` → `Next`
2. Select `Slider NS` or `Slider EW` and select char 255 (which will look special). You will see this prompt:
image
3. Once you confirm, the char displayed in the Edit Chars menu will be a magenta `???`. You can then place sliders and edit their char just like a CustomBlock. The param should also default to the regular char afterward (this won't do anything about existing sliders, though).

**Comment by flarn2006** [comment]
Oh wow, that's even better! Never knew that was a thing; thanks for
introducing me to it. :) And you're right; that makes my addition kind of
pointless :P

**Comment by asiekierka** [comment]
>since you can already effectively achieve this with regular sliders and many other types:

what

**Comment by flarn2006** [comment]
@asiekierka Oh hey, I know you from Minecraft modding. Cool you're into MZX too :)

**Comment by AliceLR** [comment]
@asiekierka Setting the char ID value of a type to 255 makes it act like a Custom* type. This has been around since 2.00 but the editor behavior and special display for it is fairly new. Before 2.84X selecting char 255 for a type in the editor would select char 1 instead and this had to be done entirely through Robotic.

**Comment by flarn2006** [comment]
@AliceLR Yeah, I'm pretty sure there hasn't been a single actual placeable object type added in all the time MZX has been open source. So I actually was thinking that maybe there's a reason for that. It was a simple enough modification though, so I figured I'd submit a PR anyway just in case. (And I'm glad I did, because I learned about a useful feature I wasn't aware of!)

Will the number of slots for types be expanded in 3.00+? And what do you mean by "downver"? Is 3.00+ not going to be compatible with old worlds?

**Comment by AliceLR** [comment]
@flarn2006 There's no plan to make types two bytes, but types 98 through 121 will be available and there's also been consideration of opening types 128-254 up as user-defined types sometime (yet to be determined) in the future. There was a fork of MegaZeux 2.82 that did something like this years ago, but using them required Forth instead of Robotic. Types >=128 would run into issues with how the char ID table is organized, so who knows what that will look like in practice.

There are plans to extend the parameter to two bytes though, but not until 3.00 or later.

**Pull request closed without merging**
