### PR TITLE
MSVC Solution Refresh

### PR DESCRIPTION
**Pull request by Spectere**
I included the file list from Elig's PR and added the changes that I suggested in #161. In addition to that, I also:

* Replaced overlay/YUV support with softscale.
* Added backslashes to the output directories to appease msbuild.
* Removed now-unused Source\Core filter from the Editor project.
* Removed packaging script since we don't carry precompiled SDL.dll libraries in the repo anymore.

One nagging issue that's making me scratch my head is that the x86 builds segfaults during the network update check, right after receiving an HTTP 200 status from the update server. The console looks like this:

````
DEBUG: Video: using 'auto_glsl' renderer.
INFO: GL driver: GeForce GTX 1080 Ti/PCIe/SSE2
DEBUG: --DNS-- Starting DNS thread 0.
DEBUG: --DNS-- New thread running.
DEBUG: --DNS-- Using DNS thread 0.
DEBUG: --DNS-- Waiting for response.
DEBUG: --DNS-- Starting lookup.
DEBUG: --DNS-- Lookup completed.
DEBUG: --DNS-- Received response (return code 0)
DEBUG: Status: HTTP/1.1 200 OK (1, 200, OK)
Segmentation fault
````

Running it through the debugger indicates that this line 998 in host.c is making it angry:

````c
        // Each pass, only decompress a maximum of BLOCK_SIZE
        stream.avail_out = BLOCK_SIZE;
        stream.next_out = (Bytef *)outbuf;

        /* Perform the inflation (this will modify avail_in and
         * next_in automatically.
         */
        ret = inflate(&stream, Z_NO_FLUSH);   /* <- This one. Right here. */
        if(ret != Z_OK && ret != Z_STREAM_END)
          return -HOST_ZLIB_INFLATE_FAILED;

        // Push the block to disk
        if(fwrite(outbuf, BLOCK_SIZE - stream.avail_out, 1, file) != 1)
          return -HOST_FWRITE_FAILED;
````

That only happens on the x86 build; the x64 build is fine. The x86 build, of course, starts and runs normally if I disabled network support.

Dunno if you'd consider this a showstopper seeing as it literally only seems to be affecting MSVC/x86, which is probably only slightly less niche than Mac/PPC. :P

### CODE REVIEW

**Comment by AliceLR** [comment]
That's odd. That's a zlib library function which makes me think either we're not setting up the z_stream correctly or something's wrong with the x86 zlib you're linking against. Or, something else is corrupting the z_stream.

**Comment by AliceLR** [comment]
Also, re: packaging, what the MSYS2 scripts do is pull a copy of the SDL2 development environment from [here](https://www.libsdl.org/download-2.0.php) during environment setup/refresh. That seems generally better than keeping a bunch of big binaries in the repo (unfortunately I think we're stuck with them sitting around anyway due to how git works :/).

**Comment by Spectere** [comment]
> That's odd. That's a zlib library function which makes me think either we're not setting up the z_stream correctly or something's wrong with the x86 zlib you're linking against. Or, something else is corrupting the z_stream.
> 
> edit: note that zlib-related crashes are a much bigger issue than network support since the new world format and PNG support both rely on it. I'd try things like loading some newer games too to see if those have problems (any of the latest BKZXes will do).

Good call! I'm also getting a zlib-related crash when I load one of those worlds. Again, only on x86.

All things considered, I'm leaning pretty heavily toward the compiled zlib library being faulty somehow. I'll try recompiling everything (I mean, everything probably needs updated anyway by this point) and try it again.

> Also, re: packaging, what the MSYS2 scripts do is pull a copy of the SDL2 development environment from [here](https://www.libsdl.org/download-2.0.php) during environment setup/refresh. That seems generally better than keeping a bunch of big binaries in the repo (unfortunately I think we're stuck with them sitting around anyway due to how git works :/).

Yep, I noticed that in the script. It also makes sense since you're always going to be getting the latest version.

Unfortunately, I don't think msbuild has any guaranteed way to fetch files. I don't want to make any part of the build process reliant on having a local copy of wget/curl and InfoZip installed. I'm not too bothered, honestly. While it was kinda cool that Visual Studio would populate the build directory like the msys script does, it's still more of a nice to have than a practical addition. If you suddenly become a raging Microsoftite and decide to start doing builds with MSVC we can worry about it then. :)

> (We need the whole development environment for MSYS2 though because, as this might have come up in the dev channel a dozen or so times, MSYS2's modified headers means it's fundamentally impossible to use their DLL and the official DLL interchangeably. That's why there's custom-definable "SDL_PREFIX" variable in the build system.)

Ugh, yeah, I remember you bringing that up.

You know what kind of builds work with official SDL DLLs? MSVC builds. :trollface:

**Comment by Spectere** [comment]
Just wanted to drop an update here because it's been a while.

I am still working on this when I have time, but I'm struggling getting the deps to build properly. Like, I can get a successful build of zlib but it's giving me a lot of really strange errors when I actually try to link them with MegaZeux. Kinda thinking I might have to roll my own project files for zlib and libpng at the very least (SDL offers their own prebuild libs and, IIRC, libvorbis/libogg has a solid set of MSVC projects).

Also, VS2019 came out For Reals™ recently, and MZX builds fine with the v141_xp toolset. Same deal, of course--x64 works great while x86 eats its own head whenever zlib tries to zlib.

**Comment by AliceLR** [comment]
How are things going with this? Should I go ahead and just merge what's here? The x86 lib problem isn't great but it might be better to treat it as a separate issue if you don't think it'll be fixed within the next couple of weeks.

**Comment by Spectere** [comment]
Yeah, I'm thinking that merging what's here makes the most sense. From what I've seen this is far from an uncommon issue, particularly with zlib, and there's a number of third-party Visual Studio solutions available for it. Naturally, none of the ones I've tried actually built a static lib that would work with MZX, but at least it made it a bit more clear that we're not the only ones who have various weird issues with this. I legit don't remember where the library in Deps.zip came from. I'm pretty sure I built it since the one that ajs built would have been several years old by that point, but it's long enough that I don't remember specifically what went into it.

Assuming I can get a project working that does what we need it to do, I think the approach that I'm going to take is just stuffing the zlib source, along with a hand-spun vcproj, into Deps.zip (or contrib, or something) and just having it build on the fly along with MZX. Not sure how you feel about git submodules, but we could just link to a particular commit from the zlib Github repo to ensure that it's pulling down the specific version we want. I dunno. We'll have to discuss at some point, as soon as I remember how to start up Discord.

**Comment by AliceLR** [comment]
Not a huge fan of submodules from what I've seen of them, though I haven't used them very much. Adding the source to the MSVC deps archive might be the right solution, but I don't know very much about the specific issue. I'll go ahead and merge this PR now.

**Pull request merged**
