### PR TITLE
MSVC 2.92 Revamp — Part Deux

### PR DESCRIPTION
**Pull request by Spectere**
A few changes:

- All of the static libraries (aside from SDL, since they provide their own prebuilt ones) have been updated and rebuilt for the vs2017-xp toolset. This resolves the zlib-related crashes that the x86 MSVC builds had.
- The 2.92 changes have been applied to the MSVC solution.
- Updater support has been removed, as MSVC MZX builds had a tendency to try to update to the latest MSYS build. This can be easily reenabled if necessary down the road.

One remaining bug: debug builds always fail with a C4703 error (possibly uninitialized pointer). This error is a false positive (from a quick glance, libvorbis is passing an uninitialized pointer by reference to a function, which initializes it, then passes the initialized pointer to another function by value—MSC incorrectly assumes that the pointer is never set) and despite not causing any issues it throws an error rather than a more sensible warning.

I'm at a loss for how to make the build system behave in a sane way when it comes to that. I turned off all of the security checks that would cause that warning to be upgraded to an error but to no avail. It doesn't impact the release builds, but it would be nice to be able to use Visual Studio's debugger down the road.

### CODE REVIEW

**Comment by AliceLR** [comment]
What's up with the NO_ERROR hack? That should probably be fixed in MZX instead.

**Comment by AliceLR** [comment]
I fixed the NO_ERROR issue in master, please merge. Thanks!

**Comment by Spectere** [comment]
`"…if MZX is built against the MZX SDK."`

Yeah, I'm just going ahead and blame sleep deprivation for everything going on there. :P

I'll check this out when I get home from work and update the MSVC branch accordingly. Everything looks good so far, though!

The fix is probably a good idea in general. I remember from other projects that clang also doesn't care much for duplicate enum values, and "NO_ERROR" is pretty ambiguous (and honestly, I don't understand why Microsoft wouldn't call it W32_NO_ERROR or something like that in Win32. Whatevs).

**Comment by Spectere** [comment]
HI I WAS AT WORK FOR 5 DAYS STRAIGHT

But yeah, here ya go. Sorry it took so long. <3

I also realized that I forgot to enable RAD support in the MSVC builds, so I went ahead and fixed that glitch as well. Release builds for x86 and x64 both seem to work without a hitch.

**Comment by AliceLR** [comment]
Thanks. I'm going to go ahead and merge this, but I'm curious what the `_ALLOW_KEYWORD_MACROS` define is needed for. Is it something we need to fix in MZX? (if it's because of the actual RAD code or in the placement new/delete stuff Lancer and I had to add then probably no...)

**Comment by Spectere** [comment]
MSVC is surprisingly strict by default when it comes to redefining C++ keywords (that behavior is undefined in C++11), and `_ALLOW_KEYWORD_MACROS` relaxes that.

Basically, the thing that's causing that to get thrown is the `#define inline __inline` in msvc.h. We're still targeting the v141-xp toolchain which still lacks the standard `inline` keyboard that C99 brought to the table and needs the #define. That toolchain supports the standard `inline` keyword for C++ code, however, so when audio_reality.cpp eventually includes msvc.h it's redefining a valid keyword and VC is throwing an error.

Now that I think about it a bit more, the most correct fix would be to lock that particular define around `#ifndef __cplusplus`. The two are almost certainly functionally equivalent, but the `#ifndef` approach smells a bit better to me. I'll test that as soon as I get a chance (hopefully in less than five days, heh) and let you know what I come up with.

**Pull request merged**
