### PR TITLE
Made MSVC solution files suck slightly less and (probably/hopefully) …

### PR DESCRIPTION
**Pull request by TheDevTeam2**
…compile (for now).

### CODE REVIEW

**Comment by AliceLR** [comment]
Still waiting for @Spectere to give this a look. The summary of what he said in PM when I originally asked about this is that this PR questionably removes support for older versions of Windows and explicitly includes dependencies it shouldn't be.

**Comment by Spectere** [comment]
Yeaaaah, sorry about that. I kept forgetting about this. Then I realized today that my copy of MSVC was horribly out of date (I mostly run Linux nowadays) so I'll have to take a closer look at this PR this weekend.

A few things that stood out to me just from checking the csproj files:

* Removing XP support. I think Microsoft still supports the XP build target in the latest Windows SDK. It's of course fine to remove this for private builds but it should be kept in any released source until it stops remaining feasible to support. To be honest, with VS2019 fully obsoleting XP support that might not take too long.

* The include and library path strings have several unnecessary paths in them. I realize that I made a mistake by not including $(SolutionDir)Deps\include\SDL2 in the include paths and $(SolutionDir)Deps\lib\<arch> in the library paths for MegaZeux and MZXRun due to how I have my systems set up (with libsdl2 being in my global include/library paths for convenience and better *nix interoperability), but that's the only additional path that's necessary if the deps are extracted in the correct place. It's best to keep this as clean as possible to ensure that future changes to the Windows SDK and/or Visual Studio don't cause solution/project file breakage.

* The target platform was bumped SDK from 7.0 to 10.0.16299.0.. Probably won't have much of an impact on the resulting build, but I prefer to keep the target SDK as old as possible to reduce the risk of breakage on older versions of Windows.

Lastly, I would appreciate it if you would be a bit more tactful with the title of your PRs and commits in the future.

**Comment by Spectere** [comment]
To add to the above: I just installed VS2019 preview 4 and XP is still supported in the VS2015 and VS2017 toolchains. I suggest that we keep XP support in the MSVC project until it's dropped from the latest mainline Visual Studio release or the mingw64 builds stop supporting it, whichever comes first. The MSVC builds should be as close in feature set and compatibility to the mingw64 builds as possible. The exception to this is if MZX starts making use of features that the VS2017 toolchain don't support, but 2017's C99 support is complete enough where that hasn't proven to be an issue.

**Comment by AliceLR** [comment]
@Spectere: please open a new pull request with your recommended changes.

**Pull request closed without merging**
