### PR TITLE
Xcode Versioning Improvement

### PR DESCRIPTION
**Pull request by Spectere**
The Xcode project now sets the VERSION macro appropriately, depending on the version set inside the Info.plist file.

I haven't yet found a reliable way of automatically setting the plist file based on the git branch without breaking signing and other nice things, but if I come across a good way of doing that I'll probably implement that next.

### CODE REVIEW

**Comment by AliceLR** [comment]
The "v" in the version is erroneous (it's just "MegaZeux #.##x"; we add the v in branch names because of how Git works) and it looks like you're still missing VERSION_DATE.  Also, please check Discord more often than never.  I mentioned this right after you made this PR. :)

**Comment by Spectere** [comment]
I did see your message, then I got busy and ultimately forgot about this entirely because I’m awesome like that. :p I try to check #mzx-development whenever I log in.

And yeah, I agree that there’s not much point in making another 2.91b release. I’ll have these fixes in place for 2.91c.

**Comment by AliceLR** [comment]
FYI, 2.91c will be happening very soon! You might also want to look at this commit, since it probably steps on you: 2e4a5f22.  The short version is the `st_load`, `hmn_load`, and `flt_load` loaders were readded and `mkstemp` was removed (it was used only in `tempfile` and was causing other problems).

**Comment by Spectere** [comment]
Heyyyy, thanks for the heads up! I'll work on getting this (and the other discussed changes) in place throughout this week.

The libxmp changes also look like they'll affect the MSVC project, so I'll get that updated as well.

**Comment by AliceLR** [comment]
I was about to merge this but it's based on the `v2.91c` branch instead of `master`.  The changes in `Makefile`, `README.md`, `src/graphics.c`, `src.updater.c`, and **especially** `version.inc` should not be here.  This is probably related to the `v2.91b` branch having been deleted.

**Pull request merged**
