### PR TITLE
Clipboard Handler Reorganization

### PR DESCRIPTION
**Pull request by Spectere**
The X11 keyboard handler doesn't seem to work particularly well in KDE Plasma 5 (you could paste from the system clipboard but not copy), so I decided to overcompensate and reorganize part of the project while fixing the glitch (i.e. making Linux use the SDL2 handler, which works fine with KDE).

Regarding other platforms: macOS/Intel already uses the SDL2 clipboard so we know that this works. Windows/MSVC does **not** like it at all and I can't find a good reason why (valgrind has nothing to say on the matter and I've triple-checked my code, so I'm pretty confident that the implementation is correct), so Windows will still use the win32 handler with this patch. I don't have a mingw64 install handy, so I haven't tried it on there yet. I'll update the MSVC and Xcode projects if this looks good to you.

Naturally, if SDL2 isn't used, platform-specific handlers are used (x11 on Unix, win32 on Windows, carbon on OS X).

Theoretically, multiple clipboard handlers could be enabled per platform and dynamically switched if desired, but that isn't implemented in this patch.

Now, without further ado, here are the list of changes:

* Split clipboard handlers into separate functions.
* The appropriate clipboard is built and assigned at compile time (can be changed in the future to allow changes via config).
* All platforms except for Win32 default to SDL2 if libsdl2 is used. System-specific clipboard handlers are avoided where possible.
* The selected clipboard handler is displayed on the console when MegaZeux is started.

### CODE REVIEW

**Comment by AliceLR** [comment]
If you're going to have separate object files, have them implement common functions and get rid of the extra headers.  There's no need for `clipboard_init` or `clipboard.o` in this case.  Honestly, there's no need for the separate objects, either, which leads me to my question: why?  This PR seems ridiculously arbitrary :P

**Comment by Spectere** [comment]
It might be a bit overkill, yeah. :P

The main intent was to allow for multiple active clipboard handlers to be compiled in at once and swapped out as needed. The reason I went with this approach was specifically because the X11 method works fine with some DEs while KDE didn't care for it much and I figured that we could end up in a situation where the opposite case is true, given how unbelievably standardized everything is when it comes to Linux desktops.

Oh, it also just occurred to me that the X11 method would probably break on Wayland-powered desktops. I have a spare laptop that I can use to test that...might try to get that together this weekend.

But anyway, I mostly wanted to get your thoughts on how you wanted to handle this going forward, as I got this to the point where it can really go either way. It would be trivial to make it an option in config.sh, for instance (maybe make SDL2 the default and offer the option to override it).

Let me know which direction you want to go with this and I'll make it happen. :)

**Comment by AliceLR** [comment]
I chatted with Lancer-X and he had a good point that "this is the kind of thing you'd contrib a library for".  Clipboard support isn't tied too deeply into MZX, especially since we pulled it out of robo_ed.c; maybe moving it to a contrib wouldn't be such a bad idea.  That could probably be said about a lot of platform compatibility code though (including the socksyms stuff I just refactored).  I'll think about it some more—feel free to suggest anything.

**Comment by Spectere** [comment]
Just changed the implementation to match what we discussed in Discord.

I haven't had a chance to test all of the different scenarios yet (all of my testing so far has been done with Linux/KDE5/SDL2) but I don't see any reason why any of the other platforms would fail (aside from me making a stupid mistake).

Xcode and MSVC project updates are pending.

**Comment by Spectere** [comment]
Xcode and MSVC projects have been updated.

I also threw the changes necessary to get 2.91c and up to compile with MSVC. I can cherry pick those into a different branch if you want them merged separately.

**Pull request merged**
