### PR TITLE
MSVC 2017 Support

### PR DESCRIPTION
**Pull request by Spectere**
This should get MegaZeux working on newer versions of Visual Studio. I also cleaned up the projects a bit so that you can make 64-bit builds.

I haven't tried doing and Linux/macOS builds against this fork, so some caution is advised. That said, there isn't much that had to be changed. This PR also addresses a possible ticking timebomb in libxmp.

### CODE REVIEW

**Comment by AliceLR** [comment]
The build scripts rely on the current contrib/precompiled-sdl path structure.  Is moving these files necessary to fix MSVC?

**Comment by Spectere** [comment]
It’ll only affect the post-build script (it just builds a convenient dist directory for release builds). I might be able to change the vcxproj files to use the old paths though. Let me give that a shot real quick.

**Comment by Spectere** [comment]
I updated the MSVC project to use the x86 path instead. Sorry about that!

**Comment by AliceLR** [comment]
No worries. That's what the PR process is for :>

**Pull request merged**
